#!/bin/bash

# File
# @description:
#     This file is for merging a perception module with a control module for end-to-end fine-tuning.
# @version: V0.10
# @author: Fangyi Zhang   email:gzzhangfangyi@gmail.com
# @acknowledgement:
#     ARC Centre of Excellence for Robotic Vision (ACRV)
#     Queensland Univsersity of Technology (QUT)
# @history:
#     V0.00   23/08/2017  developed the first version
#     V0.10   26/09/2018  re-organized


#======= Settings ===================
pnetwork="PP.t7"
cnetwork="CC.t7"
e2e_net_name="EE3.t7"
args="-pnetwork $pnetwork -cnetwork $cnetwork -e2e_net_name $e2e_net_name"
echo $args

cd deep_manipulation
torch_path=$TORCH_PATH
qlua="$torch_path/bin/qlua" # qlua normal place
luajit="$torch_path/bin/luajit" #luajit normal place
script="tool/add_control_net.lua"
if [[ "$display_avail" == 1 ]]; then
	# GUI is available
	if [ -e "$qlua" ]
	then $qlua $script $args
	else
	echo "cannot find $qlua"
	fi
else
	# GUI is not available
	if [ -e "$luajit" ]
	then $luajit $script $args
	else
	echo "cannot find $luajit"
	fi
fi
