#!/bin/bash

# File
# @description:
#     This file is for testing the connection to V-REP.
# @version: V0.10
# @author: Fangyi Zhang   email:gzzhangfangyi@gmail.com
# @acknowledgement:
#     ARC Centre of Excellence for Robotic Vision (ACRV)
#     Queensland Univsersity of Technology (QUT)
# @history:
#     V0.00   05/06/2015  developed the first version
#     V0.10   24/09/2018  re-organized


# if [ -z "$1" ]
#   then echo "Please provide the dataset name, e.g., 1DoF"; exit 0
# fi
#
# dataset_name=$1

# xhost +si:localuser:$( whoami ) >&/dev/null && {
# 	# GUI available
# 	display_avail=1
# } || {
# 	# GUI not available
# 	display_avail=0
# }
display_avail=1


#======= Dataset Settings ==================
sim_file="simulator/vrep_baxter_picking_inhand_cam"

# args="-framework $FRAMEWORK -game_path $game_path -name $agent_name -env $ENV -env_params $env_params -network $network -agent $agent -agent_params $agent_params -saveNetworkParams $save_network_params -steps $steps -eval_freq $eval_freq -eval_steps $eval_steps -prog_freq $prog_freq -save_freq $save_freq -actrep $actrep -gpu $gpu -random_starts $random_starts -pool_frms $pool_frms -seed $seed -threads $num_threads -display $display -display_avail $display_avail -plot_filename $plot_filename"
args="-sim_file $sim_file -display $display_avail"
echo $args

cd deep_manipulation
torch_path=$TORCH_PATH
qlua="$torch_path/bin/qlua" # qlua normal place
luajit="$torch_path/bin/luajit" #luajit normal place
script="main_scripts/test_vrep_interfaces.lua"
if [[ "$display_avail" == 1 ]]; then
	# GUI is available
	if [ -e "$qlua" ]
	then $qlua $script $args
	else
	echo "cannot find $qlua"
	fi
else
	# GUI is not available
	if [ -e "$luajit" ]
	then $luajit $script $args
	else
	echo "cannot find $luajit"
	fi
fi
